baseurl:
url: https://ltnog.lt

harmony:
  name:
  description: Lithuanian network operators group
  basetheme: jekyll-theme-dinky
  meta_description: > #
    Lithuanian network operators group
  author:
    name: ltnog
    email: donatas.abraitis@gmail.com
    url: http://ltnog.github.io
  google_analytics_key: G-KVKW07V96R
  show_disclaimer: false

markdown: kramdown
highlighter: rouge
permalink: pretty
theme: jekyll-theme-dinky

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

sass:
    sass_dir: assets/css/_sass
    style: compressed

plugins:
  - jekyll-feed

collections:
  events:
    output: true
