baseurl:
url: https://ltnog.lt

harmony:
  name: Lithuanian network operators group (ltnog)
  description:
  meta_description: > #
    Lithuanian network operators group
    Lietuvos tinklo operatorių grupė
    ltnog
  basetheme: minimal-mistakes-jekyll
  author:
    name: ltnog
    email: donatas.abraitis@gmail.com
    url: http://ltnog.github.io
  google_analytics_key: TBD
  show_disclaimer: false

markdown:    kramdown
highlighter: rouge
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

sass:
    sass_dir: assets/css/_sass
    style: compressed

gems:
  - jekyll-feed
